#!/usr/bin/env bash
# given subdomain

info_dns () {
RECORD_TYPE=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | awk '{print $4}' | tail -n 1)
DESTINATION=$(dig $2.$1 | grep -A1 'ANSWER SECTION' | awk '{print $5}' | tail -n 1)
echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
}
if [ $# -eq 1 ]
then
    info_dns $1 "wwww"
    info_dns $1 "lb-01"
    info_dns $1 "web-01"
    info_dns $1 "web-02"
elif [ $# -gt 1 ]
then
    info_dns $1 $2
fi
