#!/usr/bin/env bash
# redirection

path="/etc/nginx/sites-available/default"
new_direction="https://www.youtube.com/watch?v=dQw4w9WgXcQ"
location="/redirect_me"
sudo apt-get -y update
sudo apt get -y install nginx
sudo sed -i "/server_name _;/ a\\${location}" $path
