#!/usr/bin/env bash
# redirection

if [ ! -x /usr/sbin/nginx ]; then
	sudo apt -y update
	sudo apt install -y --allow-downgrades nginx
	sudo ufw allow 'Nginx HTTP'
fi
                                                                  
link="\n\tlocation /redirect_me/{\n\t\trewrite ^\/redirect_me/$ https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;\n\t}";
location="server_name _;";
                                                                  
sudo sed -i "/$location/a\\$link" /etc/nginx/sites-available/default
sudo service nginx restart
