#!/usr/bin/env bash
# install load balancer

sudo apt -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy 
sudo ufw allow 'haproxy'

echo "
listen server_request
        bind *:80
        mode http
        option httpchk
        server webserver1 18.212.203.20:80 check
        server webserver2 54.224.55.58:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg;

sudo service haproxy restart