#!/usr/bin/env bash
# install load balancer

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
confg='/etc/haproxy/haproxy.cfg'

echo "
frontend http
    bind *:80
    mode http
    default_backend icap_pool
backend icap_pool
    balance roundrobin
    mode http
    server 3884-web-01 18.212.203.20:80 check
    server 3884-web-02 54.224.55.58:80 check" | sudo tee -a $confg
sudo service haproxy restart