#!/usr/bin/env bash
# install load balancer

sudo apt -y update
sudo apt-get -y install haproxy 
echo "
listen server_request
        bind *:80
        mode http
        option httpchk
        server webserver1 35.229.20.253:80 check
        server webserver2 34.207.145.16:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg;
sudo service haproxy restart
