#!/usr/bin/env bash
# displays Holberton School 10 times.

C=0
while [ $C -lt 10 ]
do
    ((C++))
    if [[ $C -eq 4 ]]
    then
        echo "bad luck"
    elif [[ $C -eq 8 ]]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
done